# Generated by Django 3.0.5 on 2021-04-27 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_info',
        ),
    ]
