# Generated by Django 3.0.5 on 2021-04-26 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_remove_userinfo_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserInfo',
            new_name='user_info',
        ),
    ]
