# Generated by Django 3.0.5 on 2021-05-17 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_your_art', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='output',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
