# Generated by Django 3.0.5 on 2021-05-12 07:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('create_your_art', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='output',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='create_your_art.upload'),
        ),
        migrations.AlterField(
            model_name='output',
            name='style',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='create_your_art.style'),
        ),
        migrations.AlterField(
            model_name='output',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
