# Generated by Django 3.0.5 on 2021-05-09 07:21

import create_your_art.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_your_art', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='output',
            name='generate_img',
            field=models.ImageField(upload_to=create_your_art.models.get_file_output),
        ),
    ]
