# Generated by Django 3.0.5 on 2021-05-09 07:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('create_your_art', '0002_auto_20210509_1421'),
    ]

    operations = [
        migrations.CreateModel(
            name='generateNST',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='create_your_art.upload')),
                ('generate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='create_your_art.output')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
